import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";

const geist_sans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geist_mono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist_sans.variable} ${geist_mono.variable} antialiased`}
      >
        <ClerkProvider>
          <Navbar />
          <div className="flex min-h-screen">
            <SignedIn>
              <Sidebar />
            </SignedIn>
            <main className="flex-1">
              {children}
            </main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
